# Dev mode
version: '3.3'

services:
  frontend:
    container_name: mhsp_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app/src
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app/src
    command: "./entrypoint.sh"